# Fixing the ***`Key error`*** problem
---
<br/> 

### ***Problem Statement:***
*In this problem, the client receives a message “unable to connect to server”. The server log shows some **`Key error`**.*


### ***Cause:***
*The cause for this problem is the .pyc files that are automatically generated when any .py file is executed.(This is my personal observation it may be due to some other reasons too) because the .pyc files are binary files that are stored separately after execution of .py files.Even keeping .pyc files around can help speed up execution, since you don't have to recompile. If there's a .pyc file around, there should be a .py file around with the same name.*

### ***Solution Provided:***
*For now what we are doing is that we are trying to remove all .pyc files that are genrated when the **`cron_job.sh`**(This is the script that scans for avalable machines and write the map_machine_id.text file)script is exected.As the cron_job.sh file is executed after each and every 56th minutes in a hour automatically.This is written in the crontab -e script that can be found in the directory `/home/vlabs/sbhs_vlabs/sbhs` open the terminal and write **`crontab -e`**.*

*So in crontab -e we have added the the path to the script that consists of all the .pyc files(pyc-remove.sh) and executed it after each time execution of cron_job.sh script.The path to the pyc-remove.sh is added as follows in crontab.*

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  ***`56 * * * * /home/vlabs/sbhs_vlabs/sbhs/pyc-remove.sh`***

### ***Future Aspects:***
*There must be some more working on this error as the problem is solved temporarily but may be the better solution for this problem will be something else that do not related to the .pyc files as i have discussed the importance of .pyc files above in the  **Cause** section of discussion.*

<br/><br/><br/>

---




